### PR TITLE
Allow configuring custom directories for maps

### LINKED ISSUE #40: Allow setting the the Chimera map download path.
Currently it is set to `<path>/chimera/maps`. This makes sense and is fine for a default client install as it guarantees Chimera will have write access to that location. I think this is not always so ideal for the dedicated server though, as every `-path` instance would then have its own maps folder. It would also be nice to move the maps out of the path location if we do have write access to the main game directory. Paths should be either absolute or relative to the game directory.

### PR DESCRIPTION
**Pull request by pR0Ps**
This allows the map directory to be specified in the config file. It defaults to `<path>/chimera/maps` (the current location).  See #40 for details.

The first commit is a minimal change to add the functionality while the second refactors code around the `get_path`/`get_map_path` functions to make working with paths easier.

See commit messages for more details.

Fixes #40

### CODE REVIEW

**Comment by pR0Ps** [comment]
Rebased on master and added a note to the readme about the new option. At this point I think it's ready for an initial review.

Note that I typically work in higher-level languages so my use of memory and pointers might not be optimal - let me know if it should be done in a different way.

Also, I split this up into two commits so that the refactoring of the pathing can be easily removed from the PR if you're happier with how it works right now.

**Comment by Vaporeon** [comment]
Nice feature!
One suggestion, we were thinking at one point that it would be good to have a feature to change the main maps directory too. Perhaps the ini setting introduced here should be named to show that it is explicitly for Chimera's download maps directory rather than the main one.

**Comment by pR0Ps** [comment]
Sure, I can rename it, do you have any suggestions? Here's what I've got off the top my head:
 - `extra_map_path`
 - `downloaded_map_path`
 - `chimera_map_path`
 - Use `stock_map_path` for the main maps dir and keep `map_path` for the Chimera one

**Comment by Vaporeon** [comment]
I like `download_map_path` myself out of those, it best explains it.

**Comment by pR0Ps** [comment]
Rebased on master, updated to use `download_map_path`, and added the ability to change the main maps directory with a `map_path` option.

**Comment by pR0Ps** [comment]
Rebased on master, changed the hook for `{bitmaps,sounds,loc}.map` to only look in the `map_dir` (other parts of Chimera currently require them to be in this folder and I couldn't think of a good reason to change it), now only adds the maps in `download_map_path` if it's a different path than `map_dir`.

**Comment by Vaporeon** [comment]
Hi, I gave this a test and these changes break on retail and demo clients due to the fact those versions do not use loc.map.

**Comment by pR0Ps** [comment]
Fixed the signatures - tested and working on all versions

**Comment by SnowyMouse** [comment]
Merged.

**Pull request merged**
