### PR TITLE
Check if the ini path exists

### PR DESCRIPTION
**Pull request by MangoFizz**

### CODE REVIEW

**Comment by Vaporeon** [comment]
Do we want to do this? Currently it works exactly like the `-path` argument in that the directory will be created if it does not exist.

**Comment by JerryBrick** [comment]
I found that if the parent folder doesn't exist, the game just crashes. Should I change it to check only the parent directory or just close this PR?

**Comment by Vaporeon** [comment]
We should handle that somehow. Does this issue affect the `-path` argument too?

**Comment by JerryBrick** [comment]
Trying that on a fresh install of the game, it seems to be handled by stock strings.dll

image

**Comment by Vaporeon** [comment]
It probably makes sense to handle it the same way.

**Comment by JerryBrick** [comment]
Great! I'll work on it tomorrow

**Pull request closed without merging**
